"""pain column to string

Revision ID: 63cc090b621f
Revises: bedeb63d1b26
Create Date: 2026-07-08 12:40:06.438170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63cc090b621f'
down_revision: Union[str, Sequence[str], None] = 'bedeb63d1b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DailyPatients', 'pain',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('LogPatients', 'pain',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('LogPatients', 'pain',
               existing_type=sa.String(length=20),
               type_=sa.FLOAT(precision=53),
               existing_nullable=True)
    op.alter_column('DailyPatients', 'pain',
               existing_type=sa.String(length=20),
               type_=sa.FLOAT(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
