"""widen historical ed stays and weather schema

Revision ID: 30e9f38859e7
Revises: 49f0b840a9cb
Create Date: 2026-07-08 15:40:28.882800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e9f38859e7'
down_revision: Union[str, Sequence[str], None] = '49f0b840a9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DailyWeather', sa.Column('temperature_2m_min', sa.Float(), nullable=True))
    op.add_column('DailyWeather', sa.Column('temperature_2m_max', sa.Float(), nullable=True))
    op.add_column('DailyWeather', sa.Column('precipitation_sum_mm', sa.Float(), nullable=True))
    op.add_column('HistoricalEdStays', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('HistoricalEdStays', sa.Column('hadm_id', sa.BigInteger(), nullable=True))
    op.add_column('HistoricalEdStays', sa.Column('stay_id', sa.BigInteger(), nullable=True))
    op.add_column('HistoricalEdStays', sa.Column('intime', sa.DateTime(), nullable=True))
    op.add_column('HistoricalEdStays', sa.Column('outtime', sa.DateTime(), nullable=True))
    op.add_column('HistoricalEdStays', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('HistoricalEdStays', sa.Column('race', sa.String(length=100), nullable=True))
    op.add_column('HistoricalEdStays', sa.Column('arrival_transport', sa.String(length=50), nullable=True))
    op.add_column('HistoricalEdStays', sa.Column('disposition', sa.String(length=50), nullable=True))
    op.add_column('HistoricalEdStays', sa.Column('los_seconds', sa.Float(), nullable=True))
    op.add_column('HistoricalEdStays', sa.Column('season_synth', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_HistoricalEdStays_stay_id'), 'HistoricalEdStays', ['stay_id'], unique=False)
    op.create_index(op.f('ix_HistoricalEdStays_subject_id'), 'HistoricalEdStays', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_HistoricalEdStays_subject_id'), table_name='HistoricalEdStays')
    op.drop_index(op.f('ix_HistoricalEdStays_stay_id'), table_name='HistoricalEdStays')
    op.drop_column('HistoricalEdStays', 'season_synth')
    op.drop_column('HistoricalEdStays', 'los_seconds')
    op.drop_column('HistoricalEdStays', 'disposition')
    op.drop_column('HistoricalEdStays', 'arrival_transport')
    op.drop_column('HistoricalEdStays', 'race')
    op.drop_column('HistoricalEdStays', 'gender')
    op.drop_column('HistoricalEdStays', 'outtime')
    op.drop_column('HistoricalEdStays', 'intime')
    op.drop_column('HistoricalEdStays', 'stay_id')
    op.drop_column('HistoricalEdStays', 'hadm_id')
    op.drop_column('HistoricalEdStays', 'subject_id')
    op.drop_column('DailyWeather', 'precipitation_sum_mm')
    op.drop_column('DailyWeather', 'temperature_2m_max')
    op.drop_column('DailyWeather', 'temperature_2m_min')
    # ### end Alembic commands ###
