/**
 * datetime-picker.js — Replaces the native browser datetime-local picker
 * (the OS-styled calendar + scroll-wheel widget) with flatpickr
 * (js/vendor/flatpickr.js) everywhere it appears in the app, themed via
 * css/datetime-picker.css to match HCopilot's own colors.
 *
 * Every field that should use this picker is a plain <input type="text"
 * class="dt-picker" id="..."> in index.html (native datetime-local inputs
 * always show their own browser chrome even alongside a JS library, so the
 * type had to change). initDateTimePickers() wires flatpickr onto every
 * such input once, using altInput: the ORIGINAL input (same id, hidden)
 * keeps its value in "Y-m-d\TH:i" — exactly the "YYYY-MM-DDTHH:mm" format
 * the native datetime-local input used to produce — so every existing
 * `document.getElementById(id).value` READ across the codebase keeps
 * working unchanged. A separate visible input (auto-generated by flatpickr)
 * shows a friendlier formatted string to the user.
 *
 * Existing code that sets one of these fields programmatically (e.g.
 * prefilling "now" as a default, or populating an edit form) MUST call
 * setDateTimeValue(id, value) instead of `el.value = ...` — flatpickr keeps
 * its own selected-date state internally and doesn't notice a raw DOM
 * value assignment, so the picker would show a stale date next time it's
 * opened even though .value had already changed underneath it.
 *
 * A second class, `dt-picker-time`, is the same idea but time-only (no
 * calendar) — for fields like Triage Time where asking for a date is
 * pointless noise (triage always happens the same day as arrival) and
 * what actually matters is the clock time, used elsewhere purely to
 * compute a wait duration. The underlying input's value is just "H:i";
 * callers combine it with a real date themselves (see
 * _combineWithDatePart() in patients.js) before sending it anywhere that
 * expects a full timestamp.
 */

const _dtPickers = {};

function initDateTimePickers() {
    document.querySelectorAll('input.dt-picker').forEach(el => {
        if (_dtPickers[el.id]) return; // already initialized
        // Reuse whatever styling class the original input already had
        // (isbar-input / form-input / etc., depending on which form this
        // field lives in) so the visible alt input matches its surroundings.
        const ownClasses = Array.from(el.classList).filter(c => c !== 'dt-picker').join(' ');
        _dtPickers[el.id] = flatpickr(el, {
            enableTime: true,
            dateFormat: 'Y-m-d\\TH:i',
            altInput: true,
            altInputClass: (ownClasses ? ownClasses + ' ' : '') + 'dt-picker-alt',
            altFormat: 'M j, Y — h:i K',
            time_24hr: false,
            // Inline oninput="..." handlers already wired on these inputs
            // must keep firing on a picker selection exactly as they did
            // for native datetime-local input events — don't rely on
            // flatpickr's own event dispatch semantics matching that,
            // dispatch explicitly instead.
            onChange: () => {
                el.dispatchEvent(new Event('input', { bubbles: true }));
                el.dispatchEvent(new Event('change', { bubbles: true }));
            },
        });
    });
    document.querySelectorAll('input.dt-picker-time').forEach(el => {
        if (_dtPickers[el.id]) return;
        const ownClasses = Array.from(el.classList).filter(c => c !== 'dt-picker-time').join(' ');
        _dtPickers[el.id] = flatpickr(el, {
            enableTime: true,
            noCalendar: true,
            dateFormat: 'H:i',
            altInput: true,
            altInputClass: (ownClasses ? ownClasses + ' ' : '') + 'dt-picker-alt',
            altFormat: 'h:i K',
            time_24hr: false,
            onChange: () => {
                el.dispatchEvent(new Event('input', { bubbles: true }));
                el.dispatchEvent(new Event('change', { bubbles: true }));
            },
        });
    });
}

function setDateTimeValue(id, value) {
    const fp = _dtPickers[id];
    if (fp) {
        // triggerChange=false: matches a raw `el.value = ...` assignment,
        // which never fired input/change events either — only a real user
        // interaction with the picker should cascade into oninput="..."
        // handlers like patAutoOccupation(), via the onChange config below.
        if (!value) { fp.clear(false); return; }
        fp.setDate(value, false);
        return;
    }
    const el = document.getElementById(id);
    if (el) el.value = value || '';
}

document.addEventListener('DOMContentLoaded', initDateTimePickers);
