"""shift and group fk cascade rules

Revision ID: 49f0b840a9cb
Revises: 63cc090b621f
Create Date: 2026-07-08 12:58:03.951715

NOTE: hand-edited after autogenerate. SQL Server auto-generates unnamed FK
constraint names (e.g. "FK__Doctors__shift__778AC167") deterministically from
internal object IDs assigned at CREATE TABLE time — these are NOT guaranteed
to be identical across different database instances, even when created from
the exact same migration chain (confirmed: a fresh Docker SQL Server instance
generated different names than the dev database this migration was
autogenerated against). Look up each constraint's actual name at migration
run time via sys.foreign_keys instead of hardcoding the name that happened to
be assigned on one particular database.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f0b840a9cb'
down_revision: Union[str, Sequence[str], None] = '63cc090b621f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _fk_name(conn, table: str, column: str) -> str:
    result = conn.execute(sa.text("""
        SELECT fk.name
        FROM sys.foreign_keys fk
        JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
        JOIN sys.columns c ON fkc.parent_object_id = c.object_id AND fkc.parent_column_id = c.column_id
        JOIN sys.tables t ON fk.parent_object_id = t.object_id
        WHERE t.name = :table AND c.name = :column
    """), {"table": table, "column": column})
    row = result.first()
    if row is None:
        raise RuntimeError(f"No FK constraint found on {table}.{column}")
    return row[0]


def upgrade() -> None:
    conn = op.get_bind()

    op.drop_constraint(_fk_name(conn, 'Doctors', 'shift'), 'Doctors', type_='foreignkey')
    op.drop_constraint(_fk_name(conn, 'Doctors', 'work_days'), 'Doctors', type_='foreignkey')
    op.create_foreign_key(None, 'Doctors', 'Groups', ['work_days'], ['name'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'Doctors', 'Shifts', ['shift'], ['name'], onupdate='CASCADE', ondelete='SET NULL')

    op.drop_constraint(_fk_name(conn, 'Nurses', 'shift'), 'Nurses', type_='foreignkey')
    op.drop_constraint(_fk_name(conn, 'Nurses', 'group'), 'Nurses', type_='foreignkey')
    op.create_foreign_key(None, 'Nurses', 'Shifts', ['shift'], ['name'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'Nurses', 'Groups', ['group'], ['name'], onupdate='CASCADE', ondelete='SET NULL')


def downgrade() -> None:
    conn = op.get_bind()

    op.drop_constraint(_fk_name(conn, 'Nurses', 'group'), 'Nurses', type_='foreignkey')
    op.drop_constraint(_fk_name(conn, 'Nurses', 'shift'), 'Nurses', type_='foreignkey')
    op.create_foreign_key(None, 'Nurses', 'Groups', ['group'], ['name'])
    op.create_foreign_key(None, 'Nurses', 'Shifts', ['shift'], ['name'])

    op.drop_constraint(_fk_name(conn, 'Doctors', 'work_days'), 'Doctors', type_='foreignkey')
    op.drop_constraint(_fk_name(conn, 'Doctors', 'shift'), 'Doctors', type_='foreignkey')
    op.create_foreign_key(None, 'Doctors', 'Groups', ['work_days'], ['name'])
    op.create_foreign_key(None, 'Doctors', 'Shifts', ['shift'], ['name'])
