"""initial schema

Revision ID: bedeb63d1b26
Revises: 
Create Date: 2026-07-08 12:35:33.910161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bedeb63d1b26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DailyPatients',
    sa.Column('stay_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('heartrate', sa.Float(), nullable=True),
    sa.Column('resprate', sa.Float(), nullable=True),
    sa.Column('o2sat', sa.Float(), nullable=True),
    sa.Column('sbp', sa.Float(), nullable=True),
    sa.Column('dbp', sa.Float(), nullable=True),
    sa.Column('pain', sa.Float(), nullable=True),
    sa.Column('acuity', sa.Float(), nullable=True),
    sa.Column('chiefcomplaint', sa.String(length=500), nullable=True),
    sa.Column('arrival_time', sa.String(length=30), nullable=True),
    sa.Column('departure_time', sa.String(length=30), nullable=True),
    sa.Column('bed_occupation_time', sa.String(length=30), nullable=True),
    sa.Column('unurgent', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('stay_id')
    )
    op.create_index(op.f('ix_DailyPatients_subject_id'), 'DailyPatients', ['subject_id'], unique=False)
    op.create_table('DailyWeather',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('temperature_2m_mean', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DailyWeather_time'), 'DailyWeather', ['time'], unique=False)
    op.create_table('EDbeds',
    sa.Column('bed_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('bed_number', sa.String(length=50), nullable=False),
    sa.Column('bed_status', sa.String(length=20), server_default='Available', nullable=False),
    sa.Column('type', sa.String(length=20), server_default='normal', nullable=False),
    sa.CheckConstraint("bed_status IN ('Available', 'Under Repair')"),
    sa.CheckConstraint("type IN ('normal', 'monitor', 'ICU', 'chariot')"),
    sa.PrimaryKeyConstraint('bed_id'),
    sa.UniqueConstraint('bed_number')
    )
    op.create_table('Groups',
    sa.Column('group_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('days', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('HistoricalEdStays',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('intime_synth', sa.DateTime(), nullable=False),
    sa.Column('outtime_synth', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_HistoricalEdStays_intime_synth'), 'HistoricalEdStays', ['intime_synth'], unique=False)
    op.create_table('LogPatients',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('heartrate', sa.Float(), nullable=True),
    sa.Column('resprate', sa.Float(), nullable=True),
    sa.Column('o2sat', sa.Float(), nullable=True),
    sa.Column('sbp', sa.Float(), nullable=True),
    sa.Column('dbp', sa.Float(), nullable=True),
    sa.Column('pain', sa.Float(), nullable=True),
    sa.Column('acuity', sa.Float(), nullable=True),
    sa.Column('chiefcomplaint', sa.String(length=500), nullable=True),
    sa.Column('arrival_time', sa.String(length=30), nullable=True),
    sa.Column('departure_time', sa.String(length=30), nullable=True),
    sa.Column('bed_occupation_time', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_LogPatients_stay_id'), 'LogPatients', ['stay_id'], unique=False)
    op.create_index(op.f('ix_LogPatients_subject_id'), 'LogPatients', ['subject_id'], unique=False)
    op.create_table('Shifts',
    sa.Column('shift_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_hour', sa.Integer(), nullable=False),
    sa.Column('end_hour', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('shift_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('sections', sa.String(length=1000), nullable=True),
    sa.Column('settings_tabs', sa.String(length=1000), nullable=True),
    sa.Column('statistics_tabs', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Wards',
    sa.Column('ward_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ward_name', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ward_id')
    )
    op.create_table('Doctors',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('intern_or_not', sa.String(length=20), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('work_days', sa.String(length=50), nullable=True),
    sa.Column('patientNb', sa.String(length=20), nullable=True),
    sa.Column('availabilityTimeStart', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('absent', sa.String(length=10), server_default='False', nullable=False),
    sa.CheckConstraint("intern_or_not IN ('doctor', 'intern')"),
    sa.ForeignKeyConstraint(['shift'], ['Shifts.name'], ),
    sa.ForeignKeyConstraint(['work_days'], ['Groups.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Nurses',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.Column('patientNB', sa.String(length=20), nullable=True),
    sa.Column('availabilityTimeStart', sa.String(length=30), nullable=True),
    sa.Column('absent', sa.String(length=10), server_default='False', nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.CheckConstraint("role IN ('PN', 'RN', 'Bed_Admission')"),
    sa.ForeignKeyConstraint(['group'], ['Groups.name'], ),
    sa.ForeignKeyConstraint(['shift'], ['Shifts.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_bed',
    sa.Column('patient_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['EDbeds.bed_id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'bed_id')
    )
    op.create_table('ward_bed',
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['EDbeds.bed_id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['Wards.ward_id'], ),
    sa.PrimaryKeyConstraint('ward_id', 'bed_id')
    )
    op.create_table('patient_doctor',
    sa.Column('patient_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['Doctors.id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'doctor_id')
    )
    op.create_table('patient_nurse',
    sa.Column('patient_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['Nurses.id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'nurse_id')
    )
    op.create_table('ward_doctor',
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['Doctors.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['Wards.ward_id'], ),
    sa.PrimaryKeyConstraint('ward_id', 'doctor_id')
    )
    op.create_table('ward_nurse',
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['Nurses.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['Wards.ward_id'], ),
    sa.PrimaryKeyConstraint('ward_id', 'nurse_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ward_nurse')
    op.drop_table('ward_doctor')
    op.drop_table('patient_nurse')
    op.drop_table('patient_doctor')
    op.drop_table('ward_bed')
    op.drop_table('patient_bed')
    op.drop_table('Nurses')
    op.drop_table('Doctors')
    op.drop_table('Wards')
    op.drop_table('Users')
    op.drop_table('Shifts')
    op.drop_index(op.f('ix_LogPatients_subject_id'), table_name='LogPatients')
    op.drop_index(op.f('ix_LogPatients_stay_id'), table_name='LogPatients')
    op.drop_table('LogPatients')
    op.drop_index(op.f('ix_HistoricalEdStays_intime_synth'), table_name='HistoricalEdStays')
    op.drop_table('HistoricalEdStays')
    op.drop_table('Groups')
    op.drop_table('EDbeds')
    op.drop_index(op.f('ix_DailyWeather_time'), table_name='DailyWeather')
    op.drop_table('DailyWeather')
    op.drop_index(op.f('ix_DailyPatients_subject_id'), table_name='DailyPatients')
    op.drop_table('DailyPatients')
    # ### end Alembic commands ###
